apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-crds
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./packages/infra/manifests/platform/crds
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-controllers
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  path: ./packages/infra/manifests/platform/controllers
  dependsOn:
    - name: platform-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-networking
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  path: ./packages/infra/manifests/platform/networking
  dependsOn:
    - name: platform-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-previews
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./packages/infra/manifests/platform/previews
  dependsOn:
    - name: platform-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-stable
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  path: ./packages/infra/manifests/apps/stable
  dependsOn:
    - name: platform-controllers
    - name: platform-networking
  sourceRef:
    kind: GitRepository
    name: flux-system
