config:
  # Azure
  azure-native:location: westus
  azure-native:subscriptionId: 331269d5-143f-4246-b389-9c1f41bb5882
  aamini-platform:resourceGroupName: rg-aamini-staging
  aamini-platform:githubOrganizationName: aamini-stack
  aamini-platform:githubRepositoryName: projects
  aamini-platform:aksSpecs:
    maxSurge: '1'
    nodeCount: 1
    vmSize: Standard_DS2_v2
  aamini-platform:dbSpecs:
    backupRetentionDays: 7
    geoRedundantBackup: Disabled
    skuName: Standard_B1ms
    skuTier: Burstable
    storageSizeGb: 32
  aamini-platform:postgresAdmin:
    objectId: 552c4e0f-a3f1-404f-9e96-3a9fc2abb50c
    principalName: pg-aamini-staging-admins
    principalType: Group
  aamini-platform:githubApiToken:
    secure: AAABAA05jKTMKxWlaucLfunD+3C8WZfmbHk19l4blD4IQuo4ILKWCCyTG2BBHfsPMx3J71EED5xbU29PsAg7ezMUHUBj2c+mzkRAJn90HR8eapjesTA3uS4VknDYNMjEjsNNpKkryALK58UeBjq7cXS8EGBqff8sLsPh+oY=
  aamini-platform:dbPassword:
    secure: AAABANhavxle9vRY68G2bn5MmwU5iWWimsgGs6XYjHs4618sz1rwoDWUPVAWyNVx9tAxQwjw6mm59ERW+OeXcg==
