apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-release.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app-release.name" . }}
    app.kubernetes.io/instance: {{ include "app-release.name" . }}
    app: {{ include "app-release.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app-release.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app-release.name" . }}
        app.kubernetes.io/instance: {{ include "app-release.name" . }}
        app: {{ include "app-release.name" . }}
    spec:
      serviceAccountName: {{ include "app-release.name" . }}
      containers:
        - name: {{ include "app-release.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{ if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{ end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
