apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "app-release.name" . } }
  namespace: { { .Values.app.namespace } }
  annotations:
    azure.workload.identity/use: 'true'
  labels:
    app.kubernetes.io/name: { { include "app-release.name" . } }
    app.kubernetes.io/instance: { { include "app-release.name" . } }
    app: { { include "app-release.name" . } }
