apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-release.name" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "app-release.name" . }}
    app.kubernetes.io/instance: {{ include "app-release.name" . }}
    app: {{ include "app-release.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "app-release.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
