---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgCP6VM0BVgRnq4PYUK+Tj+Cx49cZgI3viaLbEiunLew+JjrNmkPeLi8hT+Kb7xqOLfWnAUpH+morHxp+Vpwn+ldoxX7wKo2lX/SH+l4W582394y5lPWckAfPHPqX0J+LRzQv1eHwUSHM2moCqNkNr66MJzMh9PctiWFOg49ghkW21JZ/Q8HVoOc8sA1Dzx2l+j4kxK9koIZrLb5KMZ0mVH6jwAQ/lBavgLazK6qRYC+C3ljzxunV9LGvgQcLpX+2/tTIEvkiqDUoYKwYC1ZYi/WBASEennKoGJKEAGJQkqvEOpQilvg5/CmwDlJ3HmjbWBdyW8fSsd+b7/okzPHsqpW285yb1MFJn/qIwLAdeQUMKy0Cp7b7kb0U7bNN5zHNjv1BS4JHkOYdvwGie59IJsas0KHlkQwOWHOp2HsrWVJiop4Vd4o4+2LwBQ9Ti+xnR0QUu/tzoS/6pH3q6qNOsuxL5d5eZvU61fz0dvClSwwuUsfnkwCIV6vKotFItJ9UGEwg83mTvnXhIiZVzKt8p/Bu1hw92nebwCqpVvrPr8NjeiW/bZ4rQQxTdeaCm2/Uv1o644ygWNmU2JhRvhH9R2OagWXp9K0+3sRN1UtU09A/KCEQCFxXdZJLz2x9/UrZgGDB9oC0bLGWc+F1lAXVACWWcDGNNrK5JU5SSCKsgFB9hVtKXjVI2qSQAc0N9PzrYmUzUZsyPeQz4GiL/nJq6BJ5WQ/6VJ20q2UBR6Pua1SnH7F33WPViYs
  template:
    metadata:
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
