apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ariaamini-com-wildcard
  namespace: networking
spec:
  secretName: ariaamini-com-tls
  dnsNames:
    - '*.ariaamini.com'
    - ariaamini.com
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: networking
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
  namespace: networking
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: networking
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: '*.ariaamini.com'
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ariaamini-com-tls
            namespace: networking
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure-root
      port: 8443
      protocol: HTTPS
      hostname: ariaamini.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ariaamini-com-tls
            namespace: networking
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-cross-namespace-gateway
  namespace: networking
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: imdbgraph
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
    - group: ''
      kind: Secret
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: '1.x'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    sources:
      - gateway-httproute
    txtOwnerId: aamini-staging
    txtPrefix: _externaldns.
    domainFilters:
      - ariaamini.com
    serviceMonitor:
      enabled: false
