import { defineConfig } from 'vite-plus'

export default defineConfig({
	pack: {
		entry: [
			'vite.shared.ts',
			'vitest.shared.ts',
			'playwright.shared.config.ts',
			'msw.ts',
			'test/browser.ts',
			'test/database.ts',
			'test/db.ts',
			'test/playwright.ts',
			'test/postgres.ts',
			'test/server.ts',
			'test/visual-page.ts',
			'setup/styles.ts',
		],
		dts: true,
		format: ['esm'],
		sourcemap: true,
		deps: {
			skipNodeModulesBundle: true,
			neverBundle: [
				'@playwright/test',
				'@rolldown/plugin-babel',
				'@tailwindcss/vite',
				'@tanstack/devtools-vite',
				'@tanstack/react-start',
				'@test/handlers',
				'@test/styles',
				'@testing-library/jest-dom',
				'@testcontainers/postgresql',
				'@vitejs/plugin-react',
				'@vitest/browser-playwright',
				'@voidzero-dev/vite-plus-core',
				'@voidzero-dev/vite-plus-test',
				'drizzle-orm',
				'drizzle-seed',
				'msw',
				'nitro',
				'pg',
				'react',
				'testcontainers',
				'vite',
				'vite-plus',
				'vite-plugin-svgr',
				'vitest',
				'vitest-browser-react',
			],
		},
	},
})
