/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingsIdRouteImport } from './routes/ratings/$id'
import { Route as ApiSuggestionsRouteImport } from './routes/api/suggestions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsIdRoute = RatingsIdRouteImport.update({
  id: '/ratings/$id',
  path: '/ratings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: '/api/suggestions',
  path: '/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/ratings/$id': typeof RatingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/ratings/$id': typeof RatingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/ratings/$id': typeof RatingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/suggestions' | '/ratings/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/suggestions' | '/ratings/$id'
  id: '__root__' | '/' | '/api/suggestions' | '/ratings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute
  RatingsIdRoute: typeof RatingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/$id': {
      id: '/ratings/$id'
      path: '/ratings/$id'
      fullPath: '/ratings/$id'
      preLoaderRoute: typeof RatingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestions': {
      id: '/api/suggestions'
      path: '/api/suggestions'
      fullPath: '/api/suggestions'
      preLoaderRoute: typeof ApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
  RatingsIdRoute: RatingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
