name: dota-visualizer
namespace: dota-visualizer
image:
  repository: aaministack.azurecr.io/dota-visualizer
  policy: dota-visualizer
stable:
  host: dota-visualizer.ariaamini.com
preview:
  enabled: true
