[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/peace-of-real-estate/Dockerfile"
buildCommand = "pnpm --filter peace-of-real-estate build"
watchPatterns = [
	"/apps/peace-of-real-estate/**",
	"/packages/**",
	"package.json",
	"pnpm-lock.yaml",
]

[deploy]
multiRegionConfig = { "us-west2" = { numReplicas = 1 } }
runtime = "V2"
numReplicas = 1
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
sleepApplication = true
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
