image:
  repository: aaministack.azurecr.io/app
  tag: latest
app:
  name: app-release
  namespace: app-release
host: ''
rootHost: ''
service:
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m
envFromSecret: ''
